-- 같은 CART_ID끼리 묶어서 NAME들을 하나의 문자열로 이어붙인다.
-- GROUP_CONCAT 이 하는 일 : 여러 행의 값을 한 줄 문자열로 합쳐주는 함수
SELECT CART_ID
FROM (
    SELECT CART_ID, GROUP_CONCAT(NAME) AS NAMES
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) TMP
WHERE NAMES LIKE '%Milk%'
    AND NAMES LIKE '%Yogurt%'
ORDER BY CART_ID;