-- 최종 출력

-- 요거트를 가지고 있는 CART_ID
SELECT Y.CART_ID
FROM
    (SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME='Yogurt'
    ) AS Y
JOIN
    (SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME='Milk') AS M
ON Y.CART_ID=M.CART_ID
ORDER BY Y.CART_ID;