SELECT AA.ID
	FROM ECOLI_DATA AA
    JOIN (SELECT A.ID
			FROM ECOLI_DATA A 
            JOIN (SELECT * FROM ECOLI_DATA WHERE PARENT_ID IS NULL) B
            ON (A.PARENT_ID=B.ID)) BB
            ON (AA.PARENT_ID=BB.ID)
	ORDER BY AA.ID;