-- SELECT * FROM OFFLINE_SALE

-- 상품 코드별 매출액(판매가 * 판매량) 합계를 출력하는 sql문

SELECT
    P.PRODUCT_CODE
    -- ,P.PRICE
    -- ,SUM(OS.SALES_AMOUNT)
    
    -- ,P.PRICE*SUM(OS.SALES_AMOUNT) AS SALES
    ,SUM(P.PRICE*OS.SALES_AMOUNT) AS SALES -- SUM방식 2
FROM PRODUCT AS P
JOIN OFFLINE_SALE AS OS
ON P.PRODUCT_ID = OS.PRODUCT_ID

GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC

/*
가격*전체물품
가격별 물량을 곱하고 합한거나

*SUM 중요
*JOIN할 때 별칭
*/