/*
SELECT * 
FROM FIRST_HALF;
*/

-- SELECT * FROM JULY;


-- 아이스크림 맛 출력
-- 7월달 아이스크림 합 구하기 (FLAVOR별로) => GROUP BY

-- 상반기 아이스크림
-- FLAVOR 기준으로 합치기

/*
SELECT 
    A.FLAVOR, (A.TOTAL_ORDER+B.JULY_SUM)  AS SUM2
FROM FIRST_HALF  AS A
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM
        FROM JULY
        GROUP BY FLAVOR
    ) AS B
    ON A.FLAVOR=B.FLAVOR
ORDER BY SUM2 DESC
LIMIT 3;
*/
    
SELECT FLAVOR
FROM (
    SELECT 
        A.FLAVOR,
        (A.TOTAL_ORDER + B.JULY_SUM) AS SUM2
    FROM FIRST_HALF AS A
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM
        FROM JULY
        GROUP BY FLAVOR
    ) AS B
    ON A.FLAVOR = B.FLAVOR
) AS TEMP
ORDER BY SUM2 DESC
LIMIT 3;



