
SELECT * FROM FIRST_HALF;

-- SELECT * FROM ICECREAM_INFO;

-- 상반기 동안, 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량



-- 1. JOIN으로 맛에 대한 성분 추출
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FH
    JOIN ICECREAM_INFO II
    ON FH.FLAVOR=II.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER