/*
SELECT TITLE, a.BOARD_ID, REPLY_ID,b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as a, USED_GOODS_REPLY as b
WHERE a.BOARD_ID=b.BOARD_ID AND a.CREATED_DATE LIKE "2022-10%"
ORDER BY b.CREATED_DATE, TITLE

*/

SELECT A.TITLE, B.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY AS B
    ON A.BOARD_ID=B.BOARD_ID
WHERE A.CREATED_DATE LIKE "2022-10%"
ORDER BY CREATED_DATE, TITLE